---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: update apt-get
  raw: sudo apt-get update

# - name: Install required software
#   apt: name={{item}} state=present
#   with_items:
#     - apache2
#     - mysql-server
#     - php5-mysql
#     - php5
#     - libapache2-mod-php5
#     - php5-mcrypt
#     - python-mysqldb
- name: install apache2
  apt: name=apache2 state=present


- name: install mysql-server
  apt: name=mysql-server state=present

- name: install php
  apt: name=php state=present

- name: install php-mysql
  apt: name=php-mysql state=present

- name: install libapache2-mod-php
  apt: name=libapache2-mod-php state=present

- name: install php-mcrypt
  apt: name=php-mcrypt state=present

- name: install python-mysqldb
  apt: name=python-mysqldb state=present



...
